name: Parallel UI Tests
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser:
          - chrome
          - firefox
          - edge
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
      - name: Install dependencies
        run: npm install
      - name: Run UI tests
        run: 'npm test -- --browser ${{ matrix.browser }}'
