name: Parallel UI Tests
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  checkout:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser:
          - chrome
          - firefox
          - edge
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
